// ============================================================
// GENERATED by website/scripts/generate_mock_documents.mjs. Do not edit by hand.
// ============================================================
// The demo patients' files (scans, reports, photos). The images are synthetic SVGs in
// public/documents/, and each one only restates what the patient's record already says.
// ============================================================

import type { PatientDocument } from '@/features/patients/api/types';

export const MOCK_DOCUMENTS: Record<string, PatientDocument[]> = {
  '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81': [
    {
      id: '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81-tsh-2026-07',
      title: 'Thyroid function test',
      kind: 'lab_report',
      src: '/documents/5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81/tsh-2026-07.svg',
      recorded_on: '2026-07-20',
      source: 'clinic_db',
      description: 'TSH 2.1 mIU/L, within the normal range.'
    },
    {
      id: '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81-tsh-2025-07',
      title: 'Thyroid function test',
      kind: 'lab_report',
      src: '/documents/5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81/tsh-2025-07.svg',
      recorded_on: '2025-07-18',
      source: 'clinic_db',
      description: 'TSH 2.4 mIU/L, within the normal range.'
    },
    {
      id: '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81-levothyroxine-rx',
      title: 'Prescription: levothyroxine',
      kind: 'prescription',
      src: '/documents/5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81/levothyroxine-rx.svg',
      recorded_on: '2024-07-15',
      source: 'clinic_db',
      description: 'Thyroid review: TSH normal, levothyroxine settled at 50 mcg once daily.'
    }
  ],
  'a4c7e2f9-3b6d-4e18-8f5a-2b9c0d1e7a52': [
    {
      id: 'a4c7e2f9-3b6d-4e18-8f5a-2b9c0d1e7a52-viral-fever-rx',
      title: 'Prescription: viral fever',
      kind: 'prescription',
      src: '/documents/a4c7e2f9-3b6d-4e18-8f5a-2b9c0d1e7a52/viral-fever-rx.svg',
      recorded_on: '2025-11-03',
      source: 'clinic_db',
      description: 'Viral fever for three days, treated with paracetamol and fluids.'
    }
  ],
  'cb2759d8-3d91-4a4d-8bd2-026f68f76426': [
    {
      id: 'cb2759d8-3d91-4a4d-8bd2-026f68f76426-penicillin-rash',
      title: 'Photo: urticarial rash',
      kind: 'photo',
      src: '/documents/cb2759d8-3d91-4a4d-8bd2-026f68f76426/penicillin-rash.svg',
      recorded_on: '2026-09-10',
      source: 'doctor_notes',
      description:
        'Hives within an hour of a penicillin injection at another clinic. Penicillin allergy recorded.'
    },
    {
      id: 'cb2759d8-3d91-4a4d-8bd2-026f68f76426-amlodipine-rx',
      title: 'Prescription: amlodipine',
      kind: 'prescription',
      src: '/documents/cb2759d8-3d91-4a4d-8bd2-026f68f76426/amlodipine-rx.svg',
      recorded_on: '2023-11-10',
      source: 'clinic_db',
      description:
        'Hypertension diagnosed at about 150/96 mmHg; amlodipine 5 mg once daily started.'
    }
  ],
  '91786a1e-1ee8-4f60-8191-8a74c0e3edd1': [
    {
      id: '91786a1e-1ee8-4f60-8191-8a74c0e3edd1-inr-2026-09',
      title: 'INR (warfarin monitoring)',
      kind: 'lab_report',
      src: '/documents/91786a1e-1ee8-4f60-8191-8a74c0e3edd1/inr-2026-09.svg',
      recorded_on: '2026-09-01',
      source: 'clinic_db',
      description: 'INR 2.4, within the target range of 2 to 3.'
    },
    {
      id: '91786a1e-1ee8-4f60-8191-8a74c0e3edd1-inr-2026-06',
      title: 'INR (warfarin monitoring)',
      kind: 'lab_report',
      src: '/documents/91786a1e-1ee8-4f60-8191-8a74c0e3edd1/inr-2026-06.svg',
      recorded_on: '2026-06-30',
      source: 'clinic_db',
      description:
        'INR 1.9, just below the target range. Warfarin unchanged; recheck in eight weeks.'
    },
    {
      id: '91786a1e-1ee8-4f60-8191-8a74c0e3edd1-af-ecg',
      title: 'ECG: atrial fibrillation',
      kind: 'ecg',
      src: '/documents/91786a1e-1ee8-4f60-8191-8a74c0e3edd1/af-ecg.svg',
      recorded_on: '2026-06-02',
      source: 'clinic_db',
      description: 'Irregular rhythm recorded at the visit where atrial fibrillation was diagnosed.'
    },
    {
      id: '91786a1e-1ee8-4f60-8191-8a74c0e3edd1-warfarin-rx',
      title: 'Prescription: warfarin',
      kind: 'prescription',
      src: '/documents/91786a1e-1ee8-4f60-8191-8a74c0e3edd1/warfarin-rx.svg',
      recorded_on: '2026-06-02',
      source: 'clinic_db',
      description: 'Warfarin 5 mg once daily started for atrial fibrillation. Target INR 2 to 3.'
    }
  ],
  '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45': [
    {
      id: '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45-hba1c-2026-01',
      title: 'HbA1c',
      kind: 'lab_report',
      src: '/documents/9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45/hba1c-2026-01.svg',
      recorded_on: '2026-01-15',
      source: 'clinic_db',
      description: 'HbA1c 8.1 %, above target and higher than the previous 7.4 %.'
    },
    {
      id: '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45-hba1c-2025-07',
      title: 'HbA1c',
      kind: 'lab_report',
      src: '/documents/9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45/hba1c-2025-07.svg',
      recorded_on: '2025-07-10',
      source: 'clinic_db',
      description: 'HbA1c 7.4 %.'
    },
    {
      id: '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45-metformin-rx',
      title: 'Prescription: metformin',
      kind: 'prescription',
      src: '/documents/9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45/metformin-rx.svg',
      recorded_on: '2023-05-18',
      source: 'clinic_db',
      description: 'Type 2 diabetes diagnosed; metformin 500 mg twice daily started.'
    }
  ],
  'b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14': [
    {
      id: 'b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14-asthma-review-rx',
      title: 'Prescription: asthma inhalers',
      kind: 'prescription',
      src: '/documents/b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14/asthma-review-rx.svg',
      recorded_on: '2025-08-20',
      source: 'clinic_db',
      description: 'Asthma well controlled at review; budesonide continued, salbutamol as needed.'
    },
    {
      id: 'b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14-asthma-flare-rx',
      title: 'Prescription: asthma flare',
      kind: 'prescription',
      src: '/documents/b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14/asthma-flare-rx.svg',
      recorded_on: '2024-12-05',
      source: 'clinic_db',
      description: 'Asthma flare after a viral chest infection; short course of oral prednisolone.'
    }
  ],
  '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8': [
    {
      id: '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8-glucose-2026-03',
      title: 'HbA1c and fasting glucose',
      kind: 'lab_report',
      src: '/documents/4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8/glucose-2026-03.svg',
      recorded_on: '2026-03-24',
      source: 'clinic_db',
      description: 'HbA1c 6.2 %, borderline, with fasting glucose 108 mg/dL. Recheck in six months.'
    },
    {
      id: '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8-lipids-2024-10',
      title: 'Cholesterol',
      kind: 'lab_report',
      src: '/documents/4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8/lipids-2024-10.svg',
      recorded_on: '2024-10-02',
      source: 'clinic_db',
      description: 'LDL cholesterol 162 mg/dL; atorvastatin started.'
    },
    {
      id: '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8-atorvastatin-rx',
      title: 'Prescription: atorvastatin',
      kind: 'prescription',
      src: '/documents/4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8/atorvastatin-rx.svg',
      recorded_on: '2024-10-02',
      source: 'clinic_db',
      description: 'Atorvastatin 10 mg once daily started for raised LDL cholesterol.'
    }
  ],
  'd81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33': [
    {
      id: 'd81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33-renal-2026-06',
      title: 'Kidney function and HbA1c',
      kind: 'lab_report',
      src: '/documents/d81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33/renal-2026-06.svg',
      recorded_on: '2026-06-18',
      source: 'clinic_db',
      description: 'eGFR 42, down from 51 in August 2025; HbA1c 7.0 %. CKD stage 3b recorded.'
    },
    {
      id: 'd81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33-renal-2025-08',
      title: 'Kidney function',
      kind: 'lab_report',
      src: '/documents/d81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33/renal-2025-08.svg',
      recorded_on: '2025-08-12',
      source: 'clinic_db',
      description: 'eGFR 51 mL/min/1.73m².'
    }
  ],
  '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47': [
    {
      id: '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47-anomaly-scan',
      title: 'Ultrasound: anomaly scan',
      kind: 'scan',
      src: '/documents/7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47/anomaly-scan.svg',
      recorded_on: '2026-08-07',
      source: 'clinic_db',
      description: 'Anomaly scan at 19 weeks, reported normal. BP 118/76 mmHg at the same check.'
    },
    {
      id: '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47-booking-bloods',
      title: 'Antenatal booking tests',
      kind: 'lab_report',
      src: '/documents/7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47/booking-bloods.svg',
      recorded_on: '2026-06-12',
      source: 'clinic_db',
      description: 'Booking visit at 11 weeks: haemoglobin 10.8 g/dL, urine protein nil.'
    },
    {
      id: '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47-antenatal-rx',
      title: 'Prescription: folic acid and iron',
      kind: 'prescription',
      src: '/documents/7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47/antenatal-rx.svg',
      recorded_on: '2026-06-12',
      source: 'clinic_db',
      description: 'Folic acid and iron started at the booking visit.'
    }
  ],
  '1e9d4c7b-6a3f-4b28-9d05-8e2c1b7a4f66': [
    {
      id: '1e9d4c7b-6a3f-4b28-9d05-8e2c1b7a4f66-ankle-sprain-advice',
      title: 'Advice: right ankle sprain',
      kind: 'prescription',
      src: '/documents/1e9d4c7b-6a3f-4b28-9d05-8e2c1b7a4f66/ankle-sprain-advice.svg',
      recorded_on: '2025-02-14',
      source: 'clinic_db',
      description:
        'Right ankle sprain playing football: rest, ice, compression, paracetamol as needed.'
    }
  ],
  'e5b8c2d1-6f4a-4b97-8e3c-0a1d2f7b9c64': [
    {
      id: 'e5b8c2d1-6f4a-4b97-8e3c-0a1d2f7b9c64-heel-ulcer',
      title: 'Photo: left heel ulcer',
      kind: 'photo',
      src: '/documents/e5b8c2d1-6f4a-4b97-8e3c-0a1d2f7b9c64/heel-ulcer.svg',
      recorded_on: '2026-09-15',
      source: 'clinic_db',
      description:
        'Diabetic foot check: small ulcer on the left heel, cleaned and dressed. Review in one week.'
    }
  ]
};
