// ============================================================
// GENERATED by website/scripts/generate_mock_triage.py. Do not edit by hand.
// ============================================================
// The demo patients' triage at check-in, computed by the backend's risk engine
// (backend/rag/risk.py) from their desk vitals, complaint and record, so the demo
// shows exactly what the real rules decide.
// ============================================================

import type { TriageAssessment } from '@/features/patients/api/types';

export const MOCK_TRIAGE: Record<string, TriageAssessment> = {
  '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 122,
      diastolic_bp: 78,
      heart_rate: 70,
      resp_rate: 14,
      temperature_c: 36.7,
      spo2: 99,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '5f8b2a3c-9e1d-4c67-b4a2-0d7e6f3c9b81',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T08:55:00+05:30'
  },
  'a4c7e2f9-3b6d-4e18-8f5a-2b9c0d1e7a52': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 2,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 1,
        temperature: 1,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 116,
      diastolic_bp: 74,
      heart_rate: 96,
      resp_rate: 18,
      temperature_c: 38.3,
      spo2: 98,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: 'a4c7e2f9-3b6d-4e18-8f5a-2b9c0d1e7a52',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T09:05:00+05:30'
  },
  'cb2759d8-3d91-4a4d-8bd2-026f68f76426': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 2,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 1,
        temperature: 1,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 138,
      diastolic_bp: 86,
      heart_rate: 94,
      resp_rate: 18,
      temperature_c: 38.4,
      spo2: 97,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: 'cb2759d8-3d91-4a4d-8bd2-026f68f76426',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T09:20:00+05:30'
  },
  '91786a1e-1ee8-4f60-8191-8a74c0e3edd1': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 1,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 1,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 142,
      diastolic_bp: 84,
      heart_rate: 92,
      resp_rate: 16,
      temperature_c: 36.6,
      spo2: 97,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '91786a1e-1ee8-4f60-8191-8a74c0e3edd1',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T09:30:00+05:30'
  },
  '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45': {
    level: 'medium',
    urgency: 'Priority: see soon, and recheck vital signs every 30 minutes while waiting.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [
      {
        level: 'medium',
        title: 'High blood sugar',
        reasons: ['random blood glucose 268 mg/dL (diabetic range is 200+)'],
        action: 'Diabetes control is poor today; review medicines and HbA1c.',
        evidence: [1],
        source: 'vitals'
      }
    ],
    gaps: [],
    vitals: {
      systolic_bp: 136,
      diastolic_bp: 84,
      heart_rate: 82,
      resp_rate: 16,
      temperature_c: 36.8,
      spo2: 98,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: 268,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '9c7aa0d7-24a7-4a0d-93f0-3695c5d4df45',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T09:40:00+05:30'
  },
  'b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 118,
      diastolic_bp: 76,
      heart_rate: 78,
      resp_rate: 16,
      temperature_c: 36.8,
      spo2: 98,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: 'b6f1c0e2-4d3a-4f7e-9a51-2c8d7e3f9a14',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T09:50:00+05:30'
  },
  '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8': {
    level: 'medium',
    urgency: 'Priority: see soon, and recheck vital signs every 30 minutes while waiting.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [
      {
        level: 'medium',
        title: 'High blood sugar',
        reasons: [
          'random blood glucose 231 mg/dL (diabetic range is 200+)',
          'no diabetes on record'
        ],
        action: 'Confirm with fasting glucose and HbA1c.',
        evidence: [],
        source: 'vitals'
      },
      {
        level: 'medium',
        title: 'Possible high blood sugar (diabetes)',
        reasons: [
          'Symptoms: always thirsty, passing urine often at night',
          'Earlier blood sugar result on record (2026-03-24: Fasting glucose 108 mg/dL.)'
        ],
        action: 'Check blood glucose now, and HbA1c.',
        evidence: [3, 4],
        source: 'red_flag'
      }
    ],
    gaps: [],
    vitals: {
      systolic_bp: 134,
      diastolic_bp: 84,
      heart_rate: 84,
      resp_rate: 16,
      temperature_c: 36.8,
      spo2: 98,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: 231,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '4a2e9d71-8c5b-4e03-b7f6-91d2a3c4e5f8',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T10:05:00+05:30'
  },
  'd81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 146,
      diastolic_bp: 88,
      heart_rate: 84,
      resp_rate: 16,
      temperature_c: 36.7,
      spo2: 97,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: 176,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: 'd81f3b6a-2e7c-4a95-8c14-6b0e9f2d7a33',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T10:15:00+05:30'
  },
  '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47': {
    level: 'critical',
    urgency:
      'Emergency: the doctor sees the patient now. Be ready to transfer to a hospital emergency department.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [
      {
        level: 'critical',
        title: 'Possible pre-eclampsia',
        reasons: [
          'blood pressure 148/96 mmHg in pregnancy',
          'with headache for four days, swollen feet',
          'Pregnancy on record (2026-06-12: Pregnancy, 26 weeks (first pregnancy; due 1 Jan 2027).)'
        ],
        action: 'Emergency: same-day obstetric assessment. Check urine protein now.',
        evidence: [1],
        source: 'vitals'
      },
      {
        level: 'medium',
        title: 'Possible high blood pressure (hypertension)',
        reasons: [
          'Blood pressure rising across visits: 118/76 (2026-08-07) → 138/88 (2026-09-11) → 148/96 (2026-09-25)'
        ],
        action:
          'Confirm with repeat readings after rest; early treatment prevents stroke and heart and kidney damage.',
        evidence: [],
        source: 'trend'
      }
    ],
    gaps: [],
    vitals: {
      systolic_bp: 148,
      diastolic_bp: 96,
      heart_rate: 90,
      resp_rate: 18,
      temperature_c: 36.9,
      spo2: 98,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '7c3a5e19-b2d4-4f86-a0e1-3f9b8c6d2e47',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T10:25:00+05:30'
  },
  '1e9d4c7b-6a3f-4b28-9d05-8e2c1b7a4f66': {
    level: 'low',
    urgency: 'Routine: normal queue order.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [],
    gaps: [],
    vitals: {
      systolic_bp: 120,
      diastolic_bp: 76,
      heart_rate: 80,
      resp_rate: 16,
      temperature_c: 37.4,
      spo2: 99,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '1e9d4c7b-6a3f-4b28-9d05-8e2c1b7a4f66',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T10:40:00+05:30'
  },
  '2d6f9a1c-7e4b-4a3d-95c8-6f1e0b2a8d19': {
    level: 'medium',
    urgency: 'Priority: see soon, and recheck vital signs every 30 minutes while waiting.',
    news2: {
      score: 0,
      band: 'low',
      points: {
        resp_rate: 0,
        spo2: 0,
        systolic_bp: 0,
        heart_rate: 0,
        temperature: 0,
        consciousness: 0,
        oxygen: 0
      },
      missing: []
    },
    findings: [
      {
        level: 'medium',
        title: 'Possible tuberculosis',
        reasons: ['Symptoms: cough for two weeks'],
        action: 'Sputum test for TB and a chest X-ray, as per the national TB programme.',
        evidence: [],
        source: 'red_flag'
      }
    ],
    gaps: [],
    vitals: {
      systolic_bp: 124,
      diastolic_bp: 80,
      heart_rate: 88,
      resp_rate: 18,
      temperature_c: 37.6,
      spo2: 97,
      on_oxygen: false,
      consciousness: 'alert',
      blood_glucose: null,
      weight_kg: 52.0
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: '2d6f9a1c-7e4b-4a3d-95c8-6f1e0b2a8d19',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T10:50:00+05:30'
  },
  'e5b8c2d1-6f4a-4b97-8e3c-0a1d2f7b9c64': {
    level: 'critical',
    urgency:
      'Emergency: the doctor sees the patient now. Be ready to transfer to a hospital emergency department.',
    news2: {
      score: 11,
      band: 'high',
      points: {
        resp_rate: 2,
        spo2: 1,
        systolic_bp: 2,
        heart_rate: 2,
        temperature: 1,
        consciousness: 3,
        oxygen: 0
      },
      missing: []
    },
    findings: [
      {
        level: 'critical',
        title: 'NEWS2 11: high clinical risk',
        reasons: [
          'breathing rate 24/min (+2)',
          'oxygen saturation 94% (+1)',
          'blood pressure 94/58 mmHg (+2)',
          'pulse 118/min (+2)',
          'temperature 38.9 °C (+1)',
          'new confusion (+3)'
        ],
        action: 'Emergency assessment now; NEWS2 7+ in hospital triggers the emergency team.',
        evidence: [],
        source: 'news2'
      },
      {
        level: 'critical',
        title: 'Possible sepsis',
        reasons: [
          'Infection signs: fever with chills since yesterday, redness and pus from the heel wound, fever (38.9 °C measured)',
          'Warning signs: breathing rate 24/min, systolic blood pressure 94 mmHg, new confusion'
        ],
        action: 'Emergency: sepsis is time-critical. Arrange hospital transfer now.',
        evidence: [],
        source: 'vitals'
      },
      {
        level: 'medium',
        title: 'High blood sugar',
        reasons: ['random blood glucose 240 mg/dL (diabetic range is 200+)'],
        action: 'Diabetes control is poor today; review medicines and HbA1c.',
        evidence: [1],
        source: 'vitals'
      }
    ],
    gaps: [],
    vitals: {
      systolic_bp: 94,
      diastolic_bp: 58,
      heart_rate: 118,
      resp_rate: 24,
      temperature_c: 38.9,
      spo2: 94,
      on_oxygen: false,
      consciousness: 'new_confusion',
      blood_glucose: 240,
      weight_kg: null
    },
    disclaimer:
      'Rule-based decision support for prioritising patients. It flags risk and cites its reasons; it does not diagnose, and the doctor makes every clinical decision.',
    patient_id: 'e5b8c2d1-6f4a-4b97-8e3c-0a1d2f7b9c64',
    visit_id: null,
    stage: 'triage',
    assessed_at: '2026-09-25T11:05:00+05:30'
  }
};
